name: Build
# To test with act: gh act --secret-file $ENV_FILE --workflows .github/workflows/unit.yml
on:
  push:
    branches:
      - main
  pull_request:

env:
  EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install sepal_ui
        run: python -m pip install "git+https://github.com/12rambau/sepal_ui.git@sepal_pre_release"
      - name: Build with sepal_ui venv
        run: module_venv
      - name: install gwb
        run: |
          echo "**********************"
          echo "*** Installing GWB ***"
          echo "**********************"
          # Last update 2021-01-12
          INSTALLER=gwb_amd64.deb
          wget https://ies-ows.jrc.ec.europa.eu/gtb/GWB/$INSTALLER
          apt-get install -y ./$INSTALLER
          rm -f ./$INSTALLER
      - name: Install nox
        run: python -m pip install nox
      - name: set entry point and run tests
        run: nox -s test_ui
